name: skin_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.2.1
  - detectron2==0.6
  - pip:
      - datasets==2.14.5
      - huggingface-hub==0.17.2
      - imageio==2.31.3
      - labelme==5.3.1
      - numpy==1.24.0
      - opencv-python==4.8.0.76
      - pandas==2.1.0
      - pillow==10.1.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - timm==0.9.7
      - torch==2.0.1
      - torchmetrics==1.1.2
      - torchsummary==1.5.1
      - torchvision==0.15.2
      - tqdm==4.65.2
